# Generated by Django 2.2.20 on 2021-06-02 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial_squashed_0006_auto_20200610_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
