# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-10 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_on']},
        ),
#        migrations.AddField(
#            model_name='application',
#            name='slug',
#            field=models.SlugField(default='foo', editable=False, unique=True),
#            preserve_default=False,
#        ),

#        migrations.RunSQL(
#            'ALTER TABLE "tickets_application" ADD COLUMN "slug" VARCHAR(50);'
#        ),
#
#        migrations.RunSQL(
#            "Update tickets_application set slug=lower(REPLACE(application,' ',''));"
#        ),
#        migrations.RunSQL(
#            '''ALTER TABLE "tickets_application" ALTER COLUMN "slug" SET NOT NULL;
#            ALTER TABLE "tickets_application" ADD CONSTRAINT
#            "application_slug_b551ad2a_uniq" UNIQUE btree ("slug");
#            ALTER TABLE "tickets_application" ALTER COLUMN "slug" DROP DEFAULT;
#            CREATE INDEX "tickets_application_slug_b551ad2a_like" ON
#            "tickets_application" btree ("slug" varchar_pattern_ops);'''
#        ),

        migrations.AlterField(
            model_name='followup',
            name='action',
            field=models.CharField(choices=[('split', 'Split'), ('closed', 'Closed'), ('no_action', 'No Action'), ('reopened', 'Re-Opened')], default='no_action', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Very Low'), (3, 'Normal'), (2, 'High'), (1, 'Critical'), (4, 'Low')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('reopened', 'Reopened'), ('split', 'Closed - Split'), ('assigned', 'Assigned'), ('duplicate', 'Closed - Duplicate'), ('new', 'New'), ('accepted', 'Accepted')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request')], default=True, max_length=10),
        ),
    ]
