# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-10 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190209_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='action',
            field=models.CharField(choices=[('re-opened', 'Re-Opened'), ('split', 'Split'), ('closed', 'Closed'), ('no_action', 'No Action')], default='no_action', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(4, 'Low'), (3, 'Normal'), (2, 'High'), (5, 'Very Low'), (1, 'Critical')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('split', 'Closed - Split'), ('duplicate', 'Closed - Duplicate'), ('re-opened', 'Re-Opened'), ('new', 'New')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('feature', 'Feature Request'), ('bug', 'Bug Report')], default=True, max_length=10),
        ),
    ]
