# Generated by Django 2.0.13 on 2019-07-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0004_auto_20190210_1942")]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="action",
            field=models.CharField(
                choices=[
                    ("no_action", "No Action"),
                    ("closed", "Closed"),
                    ("re-opened", "Re-Opened"),
                    ("split", "Split"),
                ],
                db_index=True,
                default="no_action",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Critical"),
                    (4, "Low"),
                    (5, "Very Low"),
                    (3, "Normal"),
                    (2, "High"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("split", "Closed - Split"),
                    ("accepted", "Accepted"),
                    ("assigned", "Assigned"),
                    ("duplicate", "Closed - Duplicate"),
                    ("new", "New"),
                    ("closed", "Closed"),
                    ("re-opened", "Re-Opened"),
                ],
                db_index=True,
                default=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                ],
                db_index=True,
                default=True,
                max_length=10,
            ),
        ),
    ]
