# Generated by Django 2.2.13 on 2020-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190723_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='titleid',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='followup',
            name='action',
            field=models.CharField(choices=[('split', 'Split'), ('no_action', 'No Action'), ('re-opened', 'Re-Opened'), ('closed', 'Closed')], db_index=True, default='no_action', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Critical'), (5, 'Very Low'), (2, 'High'), (4, 'Low'), (3, 'Normal')], db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('duplicate', 'Closed - Duplicate'), ('re-opened', 'Re-Opened'), ('new', 'New'), ('accepted', 'Accepted'), ('closed', 'Closed'), ('assigned', 'Assigned'), ('split', 'Closed - Split')], db_index=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('task', 'Task'), ('feature', 'Feature Request'), ('bug', 'Bug Report')], db_index=True, default=True, max_length=10),
        ),
    ]
